"""Add file_hash to document_versions

Revision ID: a4ef1267c197
Revises: 267084376617
Create Date: 2026-06-27 16:59:45.366930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ef1267c197'
down_revision: Union[str, None] = '267084376617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_document_versions_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_file_hash'))
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
